import { NextRequest, NextResponse } from 'next/server';

export async function POST(req: NextRequest) {
    try {
        const { tracks } = await req.json();
        
        if (!tracks || tracks.length === 0) {
            return NextResponse.json({ name: "My Playlist", description: "Generated by SoundSphere" });
        }

        const songList = tracks.slice(0, 15).map((t: any) => `${t.name} by ${t.artist}`).join(', ');

        const ACCOUNT_ID = process.env.CLOUDFLARE_ACCOUNT_ID;
        const API_TOKEN = process.env.CLOUDFLARE_AI_TOKEN;

        const response = await fetch(
            `https://api.cloudflare.com/client/v4/accounts/${ACCOUNT_ID}/ai/run/@cf/meta/llama-3-8b-instruct`,
            {
                method: "POST",
                headers: {
                    Authorization: `Bearer ${API_TOKEN}`,
                    "Content-Type": "application/json",
                },
                body: JSON.stringify({
                    messages: [
                        { role: "system", content: "You are a creative music curator. Respond ONLY with a valid JSON object. Do not add any conversational text before or after." },
                        { 
                            role: "user", 
                            content: `Based on these songs: ${songList}, generate a creative playlist name and a short description of maximum 9 words.
                            Return format: {"name": "...", "description": "..."}` 
                        }
                    ],
                }),
            }
        );

        const result = await response.json();
        
        // Extract JSON from AI response
        const aiText = result.result.response;
        const firstBrace = aiText.indexOf('{');
        const lastBrace = aiText.lastIndexOf('}');
        
        let cleanJson = aiText;
        if (firstBrace !== -1 && lastBrace !== -1) {
            cleanJson = aiText.substring(firstBrace, lastBrace + 1);
        }
        
        const data = JSON.parse(cleanJson);
        
        // --- BRANDING ADDITION FIX ---
        // Logic: 
        // 1. Trim spaces.
        // 2. .replace(/\.$/, '') -> Agar end mein already dot hai, toh hata do.
        // 3. Phir explicitly ". Created by SoundSphere." add karo.
        // Result: Hamesha "Description text. Created by SoundSphere." hi banega.
        
        const cleanDesc = data.description ? data.description.trim().replace(/\.$/, '') : "A custom playlist";
        data.description = `${cleanDesc}. Created by SoundSphere.`;

        return NextResponse.json(data);

    } catch (error) {
        console.error("Cloudflare AI Error:", error);
        return NextResponse.json({ 
            name: "My Vibe Mix", 
            description: "A custom mix of my top tracks. Created by SoundSphere." 
        });
    }
}